# -*- coding: utf-8 -*-
"""DocMind_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15CLe6pNt4Ndv-D5c9_u6GbtqHCcbRyZs

# 🧠 DocMind AI — RAG Document Q&A
### Run all cells top to bottom. That's it!
**Steps:**
1. Run Cell 1 (install)
2. Run Cell 2 (start app)
3. Click the public URL that appears
4. Enter your Gemini API key in the app sidebar
5. Upload your PDF → Ask questions!
"""

# CELL 1 — Install everything
!pip install -q streamlit langchain langchain-google-genai chromadb pymupdf \
    langchain-community langchain-text-splitters langchain-core \
    pyngrok
print('✅ All packages installed!')

# CELL 2 — Write the app
app_code = """
import streamlit as st
import os
import time
import fitz

from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

st.set_page_config(page_title="DocMind AI", page_icon="🧠", layout="wide")

st.markdown(\"\"\"
<style>
@import url(https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Inter:wght@300;400;500;600&display=swap);
html,body,[class*="css"]{font-family:Inter,sans-serif;background:#0a0a0f;color:#e2e8f0}
.main{background:#0a0a0f}
.msg-user{background:#1e1e2e;border-radius:12px 12px 2px 12px;padding:.8rem 1.2rem;margin:.5rem 0;margin-left:20%;border:1px solid #2d2d3f}
.msg-bot{background:#13131a;border-radius:12px 12px 12px 2px;padding:.8rem 1.2rem;margin:.5rem 0;margin-right:20%;border-left:3px solid #6ee7f7}
.msg-label{font-size:.7rem;font-family:Space Mono,monospace;color:#475569;margin-bottom:.3rem;text-transform:uppercase}
.latency{font-size:.7rem;font-family:Space Mono,monospace;color:#475569;margin-top:.4rem}
.stTextInput>div>div>input{background:#13131a!important;border:1px solid #2d2d3f!important;color:#e2e8f0!important;border-radius:8px!important}
.stButton>button{background:linear-gradient(135deg,#6ee7f7,#a78bfa)!important;color:#0a0a0f!important;border:none!important;border-radius:8px!important;font-weight:600!important}
div[data-testid="stSidebar"]{background:#0d0d14!important;border-right:1px solid #1e1e2e!important}
</style>
\"\"\", unsafe_allow_html=True)

if "chain" not in st.session_state:
    st.session_state.chain = None
if "history" not in st.session_state:
    st.session_state.history = []
if "doc_name" not in st.session_state:
    st.session_state.doc_name = None

def build_chain(pdf_bytes, filename, api_key):
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    text = "".join(p.get_text() for p in doc)
    doc.close()
    if not text.strip():
        raise ValueError("No text found in PDF.")
    chunks = RecursiveCharacterTextSplitter(
        chunk_size=500, chunk_overlap=50
    ).split_documents([Document(page_content=text, metadata={"source": filename})])
    embeddings = GoogleGenerativeAIEmbeddings(
        model="models/gemini-embedding-001",
        google_api_key=api_key
    )
    vectorstore = Chroma.from_documents(chunks, embeddings)
    retriever = vectorstore.as_retriever(search_kwargs={"k": 4})
    llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=api_key)
    prompt = ChatPromptTemplate.from_template(
        "Answer using ONLY the context below. "
        "If not found say: I dont know based on this document.\\n"
        "Context:\\n{context}\\n"
        "Question: {question}\\n"
        "Answer:"
    )
    def fmt(docs):
        return "\\n\\n".join(d.page_content for d in docs)
    chain = (
        {"context": retriever | fmt, "question": RunnablePassthrough()}
        | prompt | llm | StrOutputParser()
    )
    return chain, len(chunks)

with st.sidebar:
    st.markdown("## 🧠 DocMind AI")
    st.markdown("RAG-powered document Q&A")
    st.markdown("---")
    api_key = st.text_input("Gemini API Key", type="password", placeholder="AIza...")
    st.markdown("---")
    st.markdown("**Upload PDF**")
    uploaded = st.file_uploader("PDF", type=["pdf"], label_visibility="collapsed")
    if uploaded and api_key:
        if st.button("⚡ Process PDF"):
            with st.spinner("Embedding document..."):
                try:
                    chain, n = build_chain(uploaded.read(), uploaded.name, api_key)
                    st.session_state.chain = chain
                    st.session_state.doc_name = uploaded.name
                    st.session_state.history = []
                    st.success(f"✅ Ready! {n} chunks indexed")
                except Exception as e:
                    st.error(f"❌ {e}")
    elif uploaded and not api_key:
        st.warning("Enter API key first")
    st.markdown("---")
    if st.session_state.chain:
        st.success(f"● {st.session_state.doc_name}")
    else:
        st.info("○ No document loaded")
    if st.button("🗑 Clear Chat"):
        st.session_state.history = []
        st.rerun()
    st.markdown("---")
    st.caption("Stack: LangChain · Gemini 2.0 · ChromaDB · PyMuPDF")

st.markdown("# 🧠 DocMind AI")
st.markdown("Ask anything about your uploaded document")

if st.session_state.chain and not st.session_state.history:
    st.markdown("**💡 Quick questions:**")
    qs = [
        "What is this document about?",
        "What are the technical skills?",
        "What projects are mentioned?",
        "What is the CGPA?",
        "What is the persons name?",
        "Summarize key highlights"
    ]
    cols = st.columns(3)
    for i, q in enumerate(qs):
        with cols[i % 3]:
            if st.button(q, key=f"q{i}"):
                with st.spinner("Thinking..."):
                    t = time.time()
                    ans = st.session_state.chain.invoke(q)
                    lat = round(time.time() - t, 2)
                    st.session_state.history.append({"q": q, "a": ans, "t": lat})
                st.rerun()

if st.session_state.history:
    st.markdown("---")
    for turn in st.session_state.history:
        st.markdown(
            f'<div class="msg-user"><div class="msg-label">You</div>{turn["q"]}</div>',
            unsafe_allow_html=True
        )
        st.markdown(
            f'<div class="msg-bot"><div class="msg-label">DocMind</div>{turn["a"]}<div class="latency">⏱ {turn["t"]}s</div></div>',
            unsafe_allow_html=True
        )

st.markdown("---")
if st.session_state.chain:
    c1, c2 = st.columns([5, 1])
    with c1:
        uq = st.text_input("Ask", placeholder="Type your question...", label_visibility="collapsed")
    with c2:
        btn = st.button("Ask →")
    if btn and uq.strip():
        with st.spinner("Searching document..."):
            t = time.time()
            ans = st.session_state.chain.invoke(uq)
            lat = round(time.time() - t, 2)
            st.session_state.history.append({"q": uq, "a": ans, "t": lat})
        st.rerun()
else:
    st.info("👈 Upload a PDF and enter your Gemini API key in the sidebar to start")
"""

with open('/content/app.py', 'w') as f:
    f.write(app_code)
print('✅ app.py written successfully!')

# CELL 3 — Launch with ngrok (free account)
import subprocess, time, requests, os
from pyngrok import ngrok

os.system('pkill -f streamlit 2>/dev/null')
time.sleep(1)

# ✅ ONLY CHANGE THIS LINE — paste your authtoken from dashboard.ngrok.com
NGROK_TOKEN = "3CqMoOgs5V79JUwlqaqFWfYEgkV_7fCPh4NRTeFZHL9HpVyRE"

# Set token
ngrok.set_auth_token(NGROK_TOKEN)

# Start streamlit
proc = subprocess.Popen(
    ['streamlit', 'run', '/content/app.py',
     '--server.port=8501',
     '--server.headless=true',
     '--server.enableCORS=false',
     '--server.enableXsrfProtection=false'],
    stdout=subprocess.PIPE, stderr=subprocess.PIPE
)

# Wait for streamlit
print('⏳ Starting Streamlit...')
for i in range(15):
    time.sleep(2)
    try:
        r = requests.get('http://localhost:8501', timeout=3)
        if r.status_code == 200:
            print('✅ Streamlit is running!')
            break
    except:
        print(f'   Attempt {i+1}/15...')

# Open tunnel
public_url = ngrok.connect(8501)
print(f'\n🚀 Open this URL in your browser:')
print(f'   {public_url}')
print('\n✅ Enter Gemini API key in sidebar')
print('✅ Upload your PDF → Ask questions!')

# Kill all old ngrok tunnels
from pyngrok import ngrok
ngrok.kill()

import os
os.system("pkill -f ngrok 2>/dev/null")
os.system("pkill -f streamlit 2>/dev/null")

import time
time.sleep(3)
print("✅ All cleared! Now run Cell 3 again.")

import subprocess, time

proc = subprocess.Popen(
    ['streamlit', 'run', '/content/app.py',
     '--server.port=8501',
     '--server.headless=true'],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

time.sleep(10)

# Read output to see actual error
out, err = proc.communicate(timeout=5)
print("STDOUT:", out.decode()[:1000])
print("STDERR:", err.decode()[:1000])

# Check file exists
import os
print("File exists:", os.path.exists('/content/app.py'))
print("File size:", os.path.getsize('/content/app.py'), "bytes")

# Show first 20 lines
with open('/content/app.py') as f:
    lines = f.readlines()
print(f"Total lines: {len(lines)}")
for i, line in enumerate(lines[:20], 1):
    print(f"{i}: {line}", end="")

import os, time

# Kill streamlit and anything on port 8501
os.system("pkill -f streamlit 2>/dev/null")
os.system("fuser -k 8501/tcp 2>/dev/null")
os.system("pkill -f ngrok 2>/dev/null")

from pyngrok import ngrok
ngrok.kill()

time.sleep(4)
print("✅ All cleared!")

import subprocess, time, requests, os
from pyngrok import ngrok

NGROK_TOKEN = "3CqMoOgs5V79JUwlqaqFWfYEgkV_7fCPh4NRTeFZHL9HpVyRE"  # ← your token
ngrok.set_auth_token(NGROK_TOKEN)

# Start streamlit on a fresh port
proc = subprocess.Popen(
    ['streamlit', 'run', '/content/app.py',
     '--server.port=8502',
     '--server.headless=true',
     '--server.enableCORS=false',
     '--server.enableXsrfProtection=false'],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

print('⏳ Starting Streamlit...')
for i in range(15):
    time.sleep(2)
    try:
        r = requests.get('http://localhost:8502', timeout=3)
        if r.status_code == 200:
            print('✅ Streamlit is running!')
            break
    except:
        print(f'   Attempt {i+1}/15...')

# Kill old tunnels then connect
ngrok.kill()
time.sleep(2)
public_url = ngrok.connect(8502)
print(f'\n🚀 Your app URL: {public_url}')
print('✅ Enter Gemini API key in sidebar')
print('✅ Upload PDF → Ask questions!')

!pip install -q groq langchain-groq sentence-transformers langchain-huggingface
print("✅ Done!")

!pip install -q streamlit langchain langchain-groq chromadb pymupdf \
    langchain-community langchain-text-splitters langchain-core \
    sentence-transformers langchain-huggingface pyngrok
print("✅ Done!")

app_code = """
import streamlit as st
import os, time, fitz

from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

st.set_page_config(page_title="DocMind AI", page_icon="🧠", layout="wide")

st.markdown(\"\"\"
<style>
@import url(https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Inter:wght@300;400;500;600&display=swap);
html,body,[class*="css"]{font-family:Inter,sans-serif;background:#0a0a0f;color:#e2e8f0}
.main{background:#0a0a0f}
.msg-user{background:#1e1e2e;border-radius:12px 12px 2px 12px;padding:.8rem 1.2rem;margin:.5rem 0;margin-left:20%;border:1px solid #2d2d3f}
.msg-bot{background:#13131a;border-radius:12px 12px 12px 2px;padding:.8rem 1.2rem;margin:.5rem 0;margin-right:20%;border-left:3px solid #6ee7f7}
.msg-label{font-size:.7rem;font-family:Space Mono,monospace;color:#475569;margin-bottom:.3rem;text-transform:uppercase}
.latency{font-size:.7rem;font-family:Space Mono,monospace;color:#475569;margin-top:.4rem}
.stTextInput>div>div>input{background:#13131a!important;border:1px solid #2d2d3f!important;color:#e2e8f0!important;border-radius:8px!important}
.stButton>button{background:linear-gradient(135deg,#6ee7f7,#a78bfa)!important;color:#0a0a0f!important;border:none!important;border-radius:8px!important;font-weight:600!important}
div[data-testid="stSidebar"]{background:#0d0d14!important;border-right:1px solid #1e1e2e!important}
</style>
\"\"\", unsafe_allow_html=True)

if "chain" not in st.session_state:
    st.session_state.chain = None
if "history" not in st.session_state:
    st.session_state.history = []
if "doc_name" not in st.session_state:
    st.session_state.doc_name = None

@st.cache_resource
def get_embeddings():
    return HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

def build_chain(pdf_bytes, filename, api_key):
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    text = "".join(p.get_text() for p in doc)
    doc.close()
    if not text.strip():
        raise ValueError("No text found in PDF.")
    chunks = RecursiveCharacterTextSplitter(
        chunk_size=500, chunk_overlap=50
    ).split_documents([Document(page_content=text, metadata={"source": filename})])
    embeddings = get_embeddings()
    vectorstore = Chroma.from_documents(chunks, embeddings)
    retriever = vectorstore.as_retriever(search_kwargs={"k": 4})
    llm = ChatGroq(model="llama3-70b-8192", api_key=api_key, temperature=0)
    prompt = ChatPromptTemplate.from_template(
        "Answer using ONLY the context below. "
        "If not found say: I dont know based on this document.\\n"
        "Context:\\n{context}\\n"
        "Question: {question}\\n"
        "Answer:"
    )
    def fmt(docs):
        return "\\n\\n".join(d.page_content for d in docs)
    chain = (
        {"context": retriever | fmt, "question": RunnablePassthrough()}
        | prompt | llm | StrOutputParser()
    )
    return chain, len(chunks)

with st.sidebar:
    st.markdown("## 🧠 DocMind AI")
    st.markdown("RAG-powered document Q&A")
    st.markdown("---")
    api_key = st.text_input("Groq API Key", type="password", placeholder="gsk_...")
    st.markdown("---")
    st.markdown("**Upload PDF**")
    uploaded = st.file_uploader("PDF", type=["pdf"], label_visibility="collapsed")
    if uploaded and api_key:
        if st.button("⚡ Process PDF"):
            with st.spinner("Embedding... (first time takes ~1 min)"):
                try:
                    chain, n = build_chain(uploaded.read(), uploaded.name, api_key)
                    st.session_state.chain = chain
                    st.session_state.doc_name = uploaded.name
                    st.session_state.history = []
                    st.success(f"✅ Ready! {n} chunks indexed")
                except Exception as e:
                    st.error(f"❌ {e}")
    elif uploaded and not api_key:
        st.warning("Enter Groq API key first")
    st.markdown("---")
    if st.session_state.chain:
        st.success(f"● {st.session_state.doc_name}")
    else:
        st.info("○ No document loaded")
    if st.button("🗑 Clear Chat"):
        st.session_state.history = []
        st.rerun()
    st.markdown("---")
    st.caption("Stack: LangChain · Groq LLaMA3 · ChromaDB · HuggingFace")

st.markdown("# 🧠 DocMind AI")
st.markdown("Ask anything about your uploaded document")

if st.session_state.chain and not st.session_state.history:
    st.markdown("**💡 Quick questions:**")
    qs = [
        "What is this document about?",
        "What are the technical skills?",
        "What projects are mentioned?",
        "What is the CGPA?",
        "What is the persons name?",
        "Summarize key highlights"
    ]
    cols = st.columns(3)
    for i, q in enumerate(qs):
        with cols[i % 3]:
            if st.button(q, key=f"q{i}"):
                with st.spinner("Thinking..."):
                    t = time.time()
                    ans = st.session_state.chain.invoke(q)
                    lat = round(time.time() - t, 2)
                    st.session_state.history.append({"q": q, "a": ans, "t": lat})
                st.rerun()

if st.session_state.history:
    st.markdown("---")
    for turn in st.session_state.history:
        st.markdown(
            f'<div class="msg-user"><div class="msg-label">You</div>{turn["q"]}</div>',
            unsafe_allow_html=True
        )
        st.markdown(
            f'<div class="msg-bot"><div class="msg-label">DocMind</div>{turn["a"]}<div class="latency">⏱ {turn["t"]}s</div></div>',
            unsafe_allow_html=True
        )

st.markdown("---")
if st.session_state.chain:
    c1, c2 = st.columns([5, 1])
    with c1:
        uq = st.text_input("Ask", placeholder="Type your question...", label_visibility="collapsed")
    with c2:
        btn = st.button("Ask →")
    if btn and uq.strip():
        with st.spinner("Searching document..."):
            t = time.time()
            ans = st.session_state.chain.invoke(uq)
            lat = round(time.time() - t, 2)
            st.session_state.history.append({"q": uq, "a": ans, "t": lat})
        st.rerun()
else:
    st.info("👈 Upload a PDF and enter your Groq API key in the sidebar to start")
"""

with open('/content/app.py', 'w') as f:
    f.write(app_code)
print('✅ app.py written!')

import os, time
from pyngrok import ngrok

os.system("pkill -f streamlit 2>/dev/null")
os.system("pkill -f ngrok 2>/dev/null")
os.system("fuser -k 8501/tcp 2>/dev/null")
os.system("fuser -k 8502/tcp 2>/dev/null")
ngrok.kill()
time.sleep(4)
print("✅ All cleared!")

import subprocess, time, requests, os
from pyngrok import ngrok

# ← paste your ngrok token
NGROK_TOKEN = "3CqMoOgs5V79JUwlqaqFWfYEgkV_7fCPh4NRTeFZHL9HpVyRE"
ngrok.set_auth_token(NGROK_TOKEN)

proc = subprocess.Popen(
    ['streamlit', 'run', '/content/app.py',
     '--server.port=8502',
     '--server.headless=true',
     '--server.enableCORS=false',
     '--server.enableXsrfProtection=false'],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

print('⏳ Starting Streamlit...')
for i in range(15):
    time.sleep(2)
    try:
        r = requests.get('http://localhost:8502', timeout=3)
        if r.status_code == 200:
            print('✅ Streamlit is running!')
            break
    except:
        print(f'   Attempt {i+1}/15...')

ngrok.kill()
time.sleep(2)
public_url = ngrok.connect(8502)
print(f'\n🚀 YOUR APP URL: {public_url}')
print('\n✅ Open that URL')
print('✅ Enter Groq API key (from console.groq.com) in sidebar')
print('✅ Upload your resume PDF')
print('✅ Ask questions!')